/** @type { import("@cspell/cspell-types").CSpellUserSettings } */
module.exports = {
  description: 'envsa cspell config',
  version: '0.2',
  language: 'en',
  dictionaryDefinitions: [
    {
      name: 'envsa',
      path: './envsa-dictionary.txt',
    },
  ],
  import: [
    '@cspell/dict-aws/cspell-ext.json',
    '@cspell/dict-bash/cspell-ext.json',
    '@cspell/dict-cpp/cspell-ext.json',
    '@cspell/dict-css/cspell-ext.json',
    '@cspell/dict-docker/cspell-ext.json',
    '@cspell/dict-en_us/cspell-ext.json',
    '@cspell/dict-filetypes/cspell-ext.json',
    '@cspell/dict-fonts/cspell-ext.json',
    '@cspell/dict-fullstack/cspell-ext.json',
    '@cspell/dict-git/cspell-ext.json',
    '@cspell/dict-google/cspell-ext.json',
    '@cspell/dict-html/cspell-ext.json',
    '@cspell/dict-lorem-ipsum/cspell-ext.json',
    '@cspell/dict-node/cspell-ext.json',
    '@cspell/dict-npm/cspell-ext.json',
    '@cspell/dict-php/cspell-ext.json',
    '@cspell/dict-software-terms/cspell-ext.json',
    '@cspell/dict-svelte/cspell-ext.json',
    '@cspell/dict-typescript/cspell-ext.json',
  ],
  dictionaries: [
    'aws',
    'bash',
    'cpp',
    'css',
    'docker',
    'en_us',
    'envsa',
    'filetypes',
    'fonts',
    'fullstack',
    'git',
    'google',
    'html',
    'lorem-ipsum',
    'node',
    'npm',
    'php',
    'softwareTerms',
    'svelte',
    'typescript',
  ],
};
