/**
 * A reminder of eslint number syntax.
 *
 * 0 - 'off'
 * 1 - 'warn'
 * 2 - 'error'
 */

/* https://eslint.org/docs/latest/rules/ */

export default {
  /* https://eslint.org/docs/latest/rules/#possible-problems */
  'array-callback-return': 2,
  'no-await-in-loop': 2,
  'no-constructor-return': 2,
  'no-inner-declarations': 2,
  'no-promise-executor-return': 2,
  'no-template-curly-in-string': 2,
  'no-unexpected-multiline': 2,
  'no-unreachable-loop': 2,
  'no-unused-vars': [
    2,
    {
      argsIgnorePattern: '^_',
      varsIgnorePattern: '^_',
    },
  ],
  'no-use-before-define': 2,
  /* https://eslint.org/docs/latest/rules/#suggestions */
  camelcase: [
    2,
    {
      ignoreDestructuring: true,
      ignoreGlobals: true,
      ignoreImports: true,
      properties: 'never',
    },
  ],
  'capitalized-comments': [
    2,
    'always',
    {
      ignoreConsecutiveComments: true,
    },
  ],
  'consistent-return': 2,
  'dot-notation': 2,
  eqeqeq: 2,
  'guard-for-in': 2,
  'max-classes-per-file': [2, 1],
  'max-depth': [2, 3],
  'new-cap': 2,
  'no-alert': 2,
  'no-array-constructor': 2,
  'no-bitwise': 2,
  'no-console': 1,
  'no-continue': 2,
  'no-else-return': 2,
  'no-empty-function': 2,
  'no-eval': 2,
  'no-extend-native': 2,
  'no-extra-bind': 2,
  'no-implied-eval': 2,
  'no-iterator': 2,
  'no-labels': 2,
  'no-lone-blocks': 2,
  'no-lonely-if': 2,
  'no-loop-func': 2,
  'no-multi-assign': 2,
  'no-multi-str': 2,
  'no-nested-ternary': 2,
  'no-new': 2,
  'no-new-func': 2,
  'no-new-wrappers': 2,
  'no-object-constructor': 2,
  'no-octal-escape': 2,
  'no-param-reassign': 2,
  'no-plusplus': 2,
  'no-proto': 2,
  'no-restricted-globals': [
    2,
    {
      name: 'isFinite',
      message:
        'Use Number.isFinite instead https://github.com/airbnb/javascript#standard-library--isfinite',
    },
    {
      name: 'isNaN',
      message:
        'Use Number.isNaN instead https://github.com/airbnb/javascript#standard-library--isnan',
    },

    'addEventListener',
    'blur',
    'close',
    'closed',
    'confirm',
    'defaultStatus',
    'defaultstatus',
    'event',
    'external',
    'find',
    'focus',
    'frameElement',
    'frames',
    'history',
    'innerHeight',
    'innerWidth',
    'length',
    'location',
    'locationbar',
    'menubar',
    'moveBy',
    'moveTo',
    'name',
    'onblur',
    'onerror',
    'onfocus',
    'onload',
    'onresize',
    'onunload',
    'open',
    'opener',
    'opera',
    'outerHeight',
    'outerWidth',
    'pageXOffset',
    'pageYOffset',
    'parent',
    'print',
    'removeEventListener',
    'resizeBy',
    'resizeTo',
    'screen',
    'screenLeft',
    'screenTop',
    'screenX',
    'screenY',
    'scroll',
    'scrollbars',
    'scrollBy',
    'scrollTo',
    'scrollX',
    'scrollY',
    'self',
    'status',
    'statusbar',
    'stop',
    'toolbar',
    'top',
  ],
  'no-restricted-properties': [
    2,
    {
      message: 'arguments.callee is deprecated',
      object: 'arguments',
      property: 'callee',
    },
    {
      message: 'Please use Number.isFinite instead',
      object: 'global',
      property: 'isFinite',
    },
    {
      message: 'Please use Number.isFinite instead',
      object: 'self',
      property: 'isFinite',
    },
    {
      message: 'Please use Number.isFinite instead',
      object: 'window',
      property: 'isFinite',
    },
    {
      message: 'Please use Number.isNaN instead',
      object: 'global',
      property: 'isNaN',
    },
    {
      message: 'Please use Number.isNaN instead',
      object: 'self',
      property: 'isNaN',
    },
    {
      message: 'Please use Number.isNaN instead',
      object: 'window',
      property: 'isNaN',
    },
    {
      message: 'Please use Object.defineProperty instead.',
      property: '__defineGetter__',
    },
    {
      message: 'Please use Object.defineProperty instead.',
      property: '__defineSetter__',
    },
    {
      message: 'Use the exponentiation operator (**) instead.',
      object: 'Math',
      property: 'pow',
    },
  ],
  'no-restricted-syntax': [
    2,
    {
      selector: 'WithStatement',
      message:
        'To avoid ambiguity and potential scoping issues, the `with` statement is not allowed.',
    },
  ],
  'no-return-assign': 2,
  'no-shadow': [
    2,
    {
      allow: ['resolve', 'reject', 'done', 'next', 'err', 'error'],
      hoist: 'all',
    },
  ],
  'no-throw-literal': 2,
  'no-unneeded-ternary': 2,
  'no-unused-expressions': [
    2,
    {
      allowTaggedTemplates: true,
    },
  ],
  'no-useless-computed-key': 2,
  'no-useless-concat': 2,
  'no-useless-constructor': 2,
  'no-useless-rename': 2,
  'no-useless-return': 2,
  'no-var': 2,
  'no-void': 2,
  'object-shorthand': [
    2,
    'always',
    {
      avoidQuotes: true,
      ignoreConstructors: false,
    },
  ],
  'one-var': [2, 'never'],
  'operator-assignment': 2,
  'prefer-arrow-callback': 2,
  'prefer-const': 2,
  'prefer-destructuring': [
    2,
    {
      AssignmentExpression: {
        array: true,
        object: false,
      },
      VariableDeclarator: {
        array: false,
        object: true,
      },
    },
    {
      enforceForRenamedProperties: false,
    },
  ],
  'prefer-exponentiation-operator': 2,
  'prefer-named-capture-group': 2,
  'prefer-numeric-literals': 2,
  'prefer-object-spread': 2,
  'prefer-promise-reject-errors': 2,
  'prefer-regex-literals': [
    2,
    {
      disallowRedundantWrapping: true,
    },
  ],
  'prefer-rest-params': 2,
  'prefer-spread': 2,
  'prefer-template': 2,
  radix: 2,
  strict: [2, 'never'],
  'symbol-description': 2,
  'vars-on-top': 2,
  yoda: 2,
  /* https://eslint.org/docs/latest/rules/#layout--formatting */
  'unicode-bom': [2, 'never'],
};
